# Generated by Django 5.2.6 on 2025-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reported', 'Reported'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
