# Generated by Django 5.1.2 on 2025-08-09 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_managemember'),
        ('users', '0008_memory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='managemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managemember',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_members', to='users.userprofile'),
        ),
        migrations.DeleteModel(
            name='AllMember',
        ),
    ]
