# Generated by Django 5.1.2 on 2025-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_managemember_member_alter_managemember_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managemember',
            name='role',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
