# Generated by Django 5.1.2 on 2025-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_managemember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managemember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='active', max_length=10),
        ),
    ]
