# Generated by Django 5.1.2 on 2025-08-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_managemember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managemember',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
