# Generated by Django 5.1.2 on 2025-09-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
