# Generated by Django 5.2.6 on 2025-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
