# Generated by Django 5.2.6 on 2025-09-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='messagereport',
        ),
    ]
