# Generated by Django 5.2.6 on 2025-09-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchat'),
        ('dashboard', '0013_remove_report_messagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='messagereport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message'),
        ),
    ]
