# Generated by Django 5.2.6 on 2025-09-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_report_messagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='post_id_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
